FROM stefanscherer/node-windows:latest

#FROM node:10.15.2

# set working directory

WORKDIR /app

 

 

# install and cache app dependencies

COPY package.json /app

RUN npm install

RUN npm install -g @angular/cli@7.3.9

 

# add app

COPY . /app

EXPOSE 4200

# start app

CMD npm run start